version: '2'
services:
    cfp-app:
        image: cfp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cfp-postgresql:5432/cfp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cfp-postgresql:
        extends:
            file: postgresql.yml
            service: cfp-postgresql
